-- Create calendar settings table
CREATE TABLE IF NOT EXISTS calendar_settings_dwd2024 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  embed_code TEXT NOT NULL DEFAULT '<div class="tidycal-embed" data-path="dwd/clarity-call"></div>',
  booking_url TEXT NOT NULL DEFAULT 'https://tidycal.com/dwd/clarity-call',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable row level security
ALTER TABLE calendar_settings_dwd2024 ENABLE ROW LEVEL SECURITY;

-- Create policy for read access
CREATE POLICY "Allow public read access" ON calendar_settings_dwd2024 
FOR SELECT USING (true);

-- Create policy for insert/update access (restrict to authenticated users)
CREATE POLICY "Allow authenticated insert/update" ON calendar_settings_dwd2024 
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated update" ON calendar_settings_dwd2024 
FOR UPDATE USING (auth.role() = 'authenticated');

-- Insert default record if none exists
INSERT INTO calendar_settings_dwd2024 (embed_code, booking_url)
VALUES ('<div class="tidycal-embed" data-path="dwd/clarity-call"></div>', 'https://tidycal.com/dwd/clarity-call')
ON CONFLICT DO NOTHING;